# theme = "noctis"

# theme = "ao"
theme = "github_dark"
[editor]
line-number = "relative"  
cursorline = true           
auto-save = true            
completion-trigger-len = 1  
idle-timeout = 300          

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"C-s" = ":w" 
V = ["extend_line_below", "select_mode"]
D = ["select_all", "delete_selection"]
S-tab = "unindent"

[keys.select]
tab = "indent"
S-tab = "unindent"
